config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy

  resources :cat_rental_requests, only: [:create, :new] do
    member { post 'approve' }
    member { post 'deny' }
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root 'cats#index'
end

app/views/shared/_errors.html.erb
<% if flash[:error] %>
    <% if flash[:error].is_a?(String) %>
        <div class="error"><%= flash[:error] %></div>
    <% else %>
        <% flash[:error].each do |key, value| %>
            <% if key.is_a?(Hash) %>
                <div class="error"><%= key[:message] %></div>
            <% else %>
                <div class="error"><%= key.to_s.split('_').join(' ').capitalize %> <%= value %></div>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/shared/_login_form.html.erb
<% action_url = controller_name == 'sessions' ? session_url : users_url %>
<% submit_text = controller_name == 'sessions' ? 'Log In' : 'Create User' %>

<form action="<%= action_url %>" method="post">
    <%= form_token %>
    
    <div>
        <label for="username">Username:</label>
        <input type="text" id="username" name="user[username]" 
            <% if params.key?(:user) && params[:user].key?(:username) %>
                value="<%= params[:user][:username] %>"
            <% end %>>
    </div>

    <div>
        <label for="password">Password:</label>
        <input type="password" id="password" name="user[password]">
    </div>

    <div>
        <input type="submit" value="<%= submit_text %>">
    </div>
</form>