config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy

  resources :cat_rental_requests, only: [:create, :new] do
    member { post 'approve' }
    member { post 'deny' }
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root 'cats#index'
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w[PENDING APPROVED DENIED], message: 'Must be PENDING, APPROVED or DENIED' }
  validate :valid_dates, on: :create
  validate :does_not_overlap_approved_request, on: :create

  belongs_to :cat
  belongs_to :user
  
  def approve!
    raise 'Not Pending' unless pending?

    CatRentalRequest.transaction do
      self.status = 'APPROVED'
      self.save!

      deny_overlapping!
    end
  end

  def deny!
    self.status = 'DENIED'
    self.save
  end

  def self.cancel_expired_requests
    expired = CatRentalRequest.where('start_date < ? AND status = ?', Date.current, 'PENDING')

    expired.each { |req| req.deny! }
  end

  private

  def pending?
    self.status == 'PENDING'
  end

  def overlapping_requests
    CatRentalRequest.where(cat_id: self.cat_id)
      .where.not(id: self.id)
      .where.not('start_date > ? AND start_date > ? OR end_date < ?', self.start_date, self.end_date, self.start_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end

  def deny_overlapping!
    overlapping_pending_requests.each do |req|
      req.status = 'DENIED'
      req.save!
    end
  end

  def valid_dates
    valid = !self.start_date.nil? && !self.end_date.nil? && self.start_date >= Date.current && self.start_date <= self.end_date
    msg = 'Dates must be today or in the future'
    errors.add(:start_date, message: msg) unless valid
  end

  def does_not_overlap_approved_request
    return unless pending?

    errors.add(:start_date, message: 'Cat unavailable on those dates') if overlapping_approved_requests.exists?
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :not_logged_in, only: [:new, :create, :approve, :deny]
  before_action :not_cat_owner, only: [:approve, :deny]

  def new
    if params.key?(:cat_id)
      @rental = CatRentalRequest.new(cat_id: params[:cat_id])
    else
      @rental = CatRentalRequest.new
    end
    
    @cats = Cat.all

    render :new
  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    @rental.user_id = current_user.id
    @cats = Cat.all

    if @rental.save
      redirect_to cat_url(@rental.cat_id)
    else
      flash.now[:error] = @rental.errors.values[0]
      render :new
    end
  end
  
  def approve
    @rental = CatRentalRequest.find_by_id(params[:id])
    @rental.approve!

    redirect_to cat_url(@rental.cat_id)
  end

  def deny
    @rental = CatRentalRequest.find_by_id(params[:id])
    @rental.deny!

    redirect_to cat_url(@rental.cat_id)
  end
  
  def not_cat_owner
    return if current_user == CatRentalRequest.find_by_id(params[:id]).cat.owner
    flash[:error] = "Owner only can approve or deny"
    redirect_to request.referrer
  end

  private

  def rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

app/views/cat_rental_requests/new.html.erb
<% @title = 'Rent a Cat' %>

<h1>Rent a Cat!</h1>

<%= render 'shared/errors' %>

<form action="<%= cat_rental_requests_url %>" method="post">
    <%= form_token %>
    <div>
        <label for="cat-id">Cat</label>
        <select id="cat-id" name="rental[cat_id]">
            <option selected disabled>--Select Cat--</option>
            <% @cats.each do |cat| %>
                <option value="<%= cat.id %>" <%= "selected" if @rental.cat_id == cat.id %>>
                    <%= cat.name.capitalize %>
            </option>
            <% end %>
        </select>
    </div>

    <div>
        <label for="start-date">Start</label>
        <input type="date" id="start-date" name="rental[start_date]" min="<%= Date.current %>" value="<%= @rental.start_date || Date.current %>">
    </div>

    <div>
        <label for="end-date">End</label>
        <input type="date" id="end-date" name="rental[end_date]" min="<%= Date.current %>" value="<%= @rental.end_date || Date.current %>">
    </div>

    <div>
        <input type="submit" value="Rent Cat">
    </div>
</form>

<% content_for :footer do %>
  <p>This is the rental page</p>
<% end %>