config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy

  resources :cat_rental_requests, only: [:create, :new] do
    member { post 'approve' }
    member { post 'deny' }
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root 'cats#index'
end

app/models/cat.rb
require 'action_view'
require 'action_view/helpers'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = %w[black white grey ginger blue brown calico].freeze

  validates :birth_date, :name, :description, presence: true
  validates :color, inclusion: { in: COLORS, message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w[M F], message: 'Must be M or F' }

  belongs_to :owner,
    class_name: 'User',
    primary_key: :id,
    foreign_key: :user_id

  has_many :cat_rental_requests,
    dependent: :destroy

  def age
    time_ago_in_words(self.birth_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  helper_method :is_owner?
  before_action :not_logged_in, only: [:edit, :update, :new, :create]
  before_action :not_cat_owner, only: [:edit, :update]

  def index
    @cats = Cat.all.order('LOWER(name)')
    render :index
  end

  def show
    @cat = Cat.find_by_id(params[:id])

    if @cat
      @rentals = @cat.cat_rental_requests.order(start_date: :asc, end_date: :asc)
      @owners = @rentals.includes(:user)
      render :show
    else
      redirect_to cats_url
    end
  end

  def edit
    @cat = Cat.find_by_id(params[:id])

    render :edit
  end

  def update
    @cat = Cat.find_by_id(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:error] = @cat.errors
      render :edit
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    logger = Logger.new("my_log.txt")
    logger.info("cat creation 222")

    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    logger = Logger.new("my_log.txt")
    logger.info("cat creation 111")

    if @cat.save
      redirect_to cat_url(@cat)
    else
      logger = Logger.new("my_log.txt")
      logger.info("cat creation failed")
      flash.now[:error] = @cat.errors
      render :new
    end
  end

  def not_cat_owner
    return if is_owner?
    flash[:error] = "Only the cat's owner may update it"
    redirect_to cat_url(params[:id])
  end

  def is_owner?
    !current_user.cats.find_by_id(params[:id]).nil?
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description, :image_url)
  end
end

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% btn_text = cat.persisted? ? "Update Cat" : "Create Cat" %>

<form action="<%= action_url %>" method="post">
    <%= form_token %>
    <input type="hidden" name="_method" value=<%= form_method %>>

    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
    </div>

    <div>
        <% %w[male female].each do |gender| %>
            <input type="radio" id="<%= gender %>" name="cat[sex]" value="<%= gender[0].upcase %>" <%= "checked" if cat.sex == gender[0].upcase %>>
            <label for="<%= gender %>"><%= gender.capitalize %></label>
        <% end %>
    </div>

    <div>
        <label for="image_url">Image URL</label>
        <input type="text" id="image_url" name="cat[image_url]" value="<%= cat.image_url %>">
    </div>

    <div>
        <label for="color">Color</label>
        <select id="color" name="cat[color]">
        <option selected disabled>--Choose a color--</option>
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>" <%= "selected" if cat.color == color %>>
                <%= color.capitalize %>
            </option>
        <% end %>
        </select>
    </div>

    <div>
        <label for="birth-date">Birth Date</label>
        <input type="date" id="birth-date" name="cat[birth_date]" max="<%= Date.current %>" value="<%= cat.birth_date %>">
    </div>

    <div>
        <label for="description">Description</label>
        <textarea id="description" name="cat[description]"><%= cat.description %></textarea>
    </div>

    <div>
        <input type="submit" value=<%= btn_text %>>
    </div>
</form>

app/views/cats/_rentals.html.erb
<table>
    <thead>
    <tr>
        <% ['Requestor', 'Start Date', 'End Date', 'Status'].each do |title| %>
            <th scope="col"><%= title %></th>
        <% end %>
    </tr>
    </thead>
    
    <tbody>
        <% rentals.each_with_index do |rental, idx| %>
            <tr>
                <td data-label="Requestor"><%= owners[idx].user.username %></td>
                <td data-label="Start Date"><%= rental.start_date %></td>
                <td data-label="End Date"><%= rental.end_date %></td>
                <td data-label="Status">
                    <% if current_user && rental.status == "PENDING" && is_owner? %>
                        <div class="stacked-btns">
                            <%= button_to 'Approve', approve_cat_rental_request_url(rental.id) %>
                            <%= button_to 'Deny', deny_cat_rental_request_url(rental.id) %>
                        </div>
                    <% else %>
                        <%= rental.status %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/cats/edit.html.erb
<% @title = "Update #{@cat.name}" %>

<h1>Edit a Cat!</h1>
<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

<% content_for :footer do %>
  <p>This is the edit page</p>
<% end %>

app/views/cats/index.html.erb
<% @title = 'Home' %>

<h1>Furrly Pals!</h1>

<%= link_to 'Add New Cat', new_cat_url, class: "add-cat" %>
<section class="all-cats">
    <% @cats.each do |cat| %>
        <div class="cat-home">
            <img src="<%= cat.image_url %>" alt="Cute Cat Photo">
            <%= link_to cat.name, cat_url(cat) %>
        </div>
    <% end %>
</section>

<% content_for :footer do %>
    <p>This is the index page</p>
<% end %>

app/views/cats/new.html.erb
<% @title = 'Add a Cat' %>

<h1>Add a Cat!</h1>

<%= render 'shared/errors' %>
<%= render "form", cat: @cat %>

<% content_for :footer do %>
    <p>This is add a cat</p>
<% end %>

app/views/cats/show.html.erb
<% @title = "#{@cat.name}" %>

<h1><%= @cat.name %></h1>

<%= render 'shared/errors' %>

<section class="cat-info">

    <img src="<%= @cat.image_url %>" alt="Photo of #{<%= @cat.name %>}">

    <% %w[birth_date age sex color description].each do |attr| %>
        <div>
            <p class="title"><%= attr.split('_').map(&:capitalize).join(' ') %></p>
            <p><%= @cat.send(attr).to_s.capitalize %></p>
        </div>
    <% end %>

    <%= link_to "Update #{@cat.name}", edit_cat_url(@cat) %>
</section>

<section class="cat-info">
    <h2>Rental Requests</h2>

    <% if @rentals.empty? %>
        <div class="msg">No one has requested this cat yet. Why not be the first!</div>
    <% else %>
        <%= render 'rentals', rentals: @rentals, owners: @owners %>
    <% end %>

    <%= link_to "Request #{@cat.name}", new_cat_rental_request_url(cat_id: @cat.id) %>
</section>

<% content_for :footer do %>
    <p>See a cat</p>
<% end %>